//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitualPetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int PetID { get; set; }
        public string PetName { get; set; }
        public System.DateTime PetAge { get; set; }
        public int PetType { get; set; }
        public int HungerLevel { get; set; }
        public int ThirstLevel { get; set; }
        public int BoredomLevel { get; set; }
        public int SicknessLevel { get; set; }
        public int WasteLevel { get; set; }
    
        public virtual AnimalType AnimalType { get; set; }
    }
}
